### ISSUE TITLE
Difference in refunding and voiding a charge?

### ISSUE THREAD

**Issue by holgersindbaek** [reverbdotcom/affirm-ruby#7]
What exactly is the difference and when can you do what?

**Comment by joekur** [comment]
It works pretty much the same to credit card processing. You can only void a charge before it has been captured. You can refund after it has been captured. Only refunds can be made partially.

From their docs:
https://docs.affirm.com/v2/api/charges/#voiding-a-charge
https://docs.affirm.com/v2/api/charges/#refunding-a-charge

**Comment by holgersindbaek** [comment]
Ok... thanks for the quick response. Can I also refund a charge that has not been captured yet?

**Comment by joekur** [comment]
No, if it has not been captured you can only void it.

**Comment by holgersindbaek** [comment]
Ok... I understand now. Thanks.
